version: '3'

services:

  productsMicroservice:
    # this is the "repository" name.
    image: microservice
    # custom container name (rather than the generated default)
    container_name: microservice
    restart: unless-stopped
    build: .
    environment:
      FLASK_ENV: "production"
    ports:
      - "0.0.0.0:80:80"